# Generated by Django 5.2.8 on 2025-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='document_number',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='e_mail',
            field=models.DateField(null=True),
        ),
    ]
