# Generated by Django 5.2.8 on 2025-11-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_address_member_document_number_member_e_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='e_mail',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='document_number',
            field=models.IntegerField(null=True),
        ),
    ]
